"""fix_knowlege_base

Revision ID: 4fcb58065025
Revises: 6bfb9e4a9f51
Create Date: 2023-06-13 13:47:10.539116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcb58065025'
down_revision = '6bfb9e4a9f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('knowledge_base', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('knowledge_base', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'knowledge_base', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('knowledge_base', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'created_at')
    op.drop_column('knowledge_base', 'file_name')
    op.drop_column('knowledge_base', 'user_id')
    # ### end Alembic commands ###
